name = "dns-buster"
type = "javascript"
compatibility_date = "2025-10-04"

main = "src/dns-buster.js"

[[routes]]
pattern = "worker.infosecuriosity.co.uk/dns-buster*"
custom_domain = true

workers_dev=false