name = "dns-buster"
main = "src/dns-buster.js"
compatibility_date = "2023-09-01"

# Attach to your subdomain
routes = [
  { pattern = "worker.infosecuriosity.co.uk/dns-buster/*", zone_name = "worker.infosecuriosity.co.uk" }
]
